Modulo Pedidos
RubizZ/Trendy pull request #30
Opened 2024-04-23 21:56 UTC by RubizZ

Creación del negocio y la integración con patrones de diseño J2EE

- DAO (Data Access Object)
- TO (Transfer Object)
- BO (Business Object)
- SA (Service Application)
- TOA (Transfer Object Assembler)
- Business Delegate

2024-04-25 08:21 UTC, Jaavii16 commented on src/integracion/DAOPedidosImp.java
> +                    + toaCestaUsuario.getTOCesta().getIDCesta() + "', '"
Cuando insertas enteros en sql no van entre comillas

2024-04-25 08:43 UTC, Jaavii16 requested changes
Revisar lo de las comillas  de los enteros en las sentencias sql

2024-04-25 09:34 UTC, Jaavii16 approved these changes
Muy bien tio, todo arreglado

2024-04-29 13:31 UTC, aibanarias approved these changes

2024-04-30 08:29 UTC, Jaavii16 approved these changes
okokokokok

2024-04-30 08:30 UTC, merged